# -*- coding: utf-8 -*-
"""Leonardo Fukuhara M14 Exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epOKF2Xtw70xnlprFcNCi7A5oKupKQzN

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Análise de Dados: Visualização de Dados I
Caderno de **Exercícios**<br>
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Pacote Seaborn;</li>
  <li>Categorias: Gráficos de Barras e de Setores;</li>
  <li>Tendências: Gráficos de Linha e de Área.</li>
</ol>

---

# **Exercícios**

Nestes exercícios, você deve decidir qual é o gráfico visto em aula que melhor visualiza uma base de dados. Após decidir, você deverá criar a visualização usando o conteúdo exposto durante a aula e adicionar um pequeno parágrafo sobre um insights que pode ser extraido do gráfico.

## 1\. Preço do diamante por tipo de corte
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data_diamonds = sns.load_dataset("diamonds")
data_diamonds.head()

# gráfico do exercício 1

grafico_diamonds = sns.barplot(x='cut', y='price', edgecolor='k', data=data_diamonds)
grafico_diamonds.set(ylim = [0,5000]);

"""**Insight do gráfico 1**: O tipo de corte Contribui no valor dos diamantes, sendo o mais caro ***Premium***, e o mais barato  ***Ideal***

---

## 2\. Número de passageiros em dezembro por ano
"""

import seaborn as sns

data = sns.load_dataset("flights")
data.head()

# gráfico do exercício 2
import numpy as np

flights = data.query('month == "Dec"')

with sns.axes_style('whitegrid'):
  grafico_flights = sns.lineplot(x='year', y='passengers', data=flights);
  grafico_flights.set(title = 'Número de passageiros em dezembro por ano',
                      xlabel = 'Ano',
                      ylabel = 'Passageiros',
                      ylim = [100, 500]);
  grafico_flights.grid(alpha=0.35)
  plt.xticks(np.arange(1949,1961,1))

"""**Insight do gráfico 2**: O número de passegeiros em dezembro, por ano, parece aumentar ao longo to tempo. Encontra-se apenas uma exceção entre os anos 1957-1958, onde o número de passageiros se manteve entre 300 e 350.

---

## 3\. Numero de passageiros por mês entre 1949 e 1959
"""

import seaborn as sns

data = sns.load_dataset("flights")
data.head()

# gráfico do exercício 3
flights_month = data.query('year >= 1949 and year <= 1959')

with sns.axes_style('whitegrid'):
  grafico_flights_month = sns.lineplot(x='month', y='passengers', hue='year', data=flights_month);
  grafico_flights_month.set(title = 'Número de passageiros por mês',
                      xlabel = 'Mês',
                      ylabel = 'Passageiros')
  grafico_flights_month.grid(alpha=0.35)
  grafico_flights_month.legend(title='Ano',loc=[1.01,0])

"""**Insight do gráfico 3**: Os anos apresentam uma mesma tendência quanto ao número de passageiros ao mês. Setembro a Novembro são meses de baixa. Já os meses de Março, Agosto e Dezembro são meses de alta.

---
"""
